build:
    environment:
        php:
            version: 8.2
    dependencies:
        before:
            - sudo apt-get update
            - sudo apt-get install -y software-properties-common
            - sudo add-apt-repository ppa:ondrej/php -y
            - sudo apt-get install -y openssl libssl-dev
            - openssl version
            - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
            - export OPENSSL_CFLAGS="-I/usr/local/include"
            - export OPENSSL_LIBS="-L/usr/local/lib -lssl -lcrypto"
    tests:
        override:
            - vendor/bin/phpunit
tools:
    php_analyzer:
        enabled: true
    php_cs_fixer:
        enabled: true
