version: "3"

environment:
  php:
    version: "8.2"
    extensions:
      - openssl

project_setup:
  commands:
    - apt-get update
    - apt-get install -y openssl

tests:
  run:
    command: vendor/bin/phpunit
  before: composer install
